[increment14]
iddanilov/metricsAndAlerting pull request #11
Opened 2023-01-19 20:29 UTC by iddanilov

2023-02-05 18:12 UTC, shmel1k requested changes

2023-02-05 18:12 UTC, shmel1k commented on internal/agent/client.go
> +// Package client - package clint application
`clint` -> `client`

2023-02-05 18:12 UTC, shmel1k commented on internal/agent/client.go
> +// Make config and client methods
`Makes config`

2023-02-05 18:12 UTC, shmel1k commented on internal/agent/client.go
> +// Make config and client methods
Но лучше -- `Prepares config ...`

2023-02-05 18:12 UTC, shmel1k commented on internal/server/example_test.go
> +	}
Не обязательно передавать ссылку на мьютекс

2023-02-05 18:12 UTC, shmel1k commented on internal/server/example_test.go
> +	}
Так как ниже Storage используется по указателю, то и ссылку на мюьтекс можно не держать. Просто 

```go
type Storage struct {
   // 
   mu sync.Mutex
}
```

2023-02-05 18:12 UTC, shmel1k commented on internal/server/handlers.go
>  		err := errors.New("can't connect to db")
Лучше вынести это в константы

2023-02-05 18:12 UTC, shmel1k commented on cmd/agent/main.go
> +	http.ListenAndServe(addr, nil)
Это не совсем graceful-shutdown приложения, поскольку выше явно вызывается os.Exit(0). При этом не происходит ожидания завершения работы остальных горутин(например, хттп сервера)

2023-02-13 11:07 UTC, iddanilov commented on internal/agent/client.go
> +// Package client - package clint application
Поправил!

2023-02-13 11:08 UTC, iddanilov commented on internal/agent/client.go
> +// Make config and client methods
Согласен, поправил!

2023-02-13 11:11 UTC, iddanilov commented on internal/server/example_test.go
> +	}
Поправил!

2023-02-13 11:12 UTC, iddanilov commented on cmd/agent/main.go
> +	http.ListenAndServe(addr, nil)
Это решение только для профелирования. В целом этом месте вызов http-сервер не нужен

2023-02-13 14:03 UTC, shmel1k requested changes

2023-02-13 14:03 UTC, shmel1k commented on internal/server/handlers_test.go
> +				Mutex:   mu,
Не нужно инициализировать это поле. Просто не выставляйте -- и всё будет работать(по идее)

2023-02-13 14:03 UTC, shmel1k commented on internal/server/storage.go
> +	Mutex   sync.Mutex
Я бы не делал это экспортируемым

2023-02-15 07:06 UTC, iddanilov commented on internal/server/handlers_test.go
> +				Mutex:   mu,
Убрал!

2023-02-15 07:10 UTC, iddanilov commented on internal/server/storage.go
> +	Mutex   sync.Mutex
Да, согласен!

2023-02-16 06:31 UTC, shmel1k approved these changes

2023-02-16 06:31 UTC, shmel1k commented on internal/server/storage.go
> +	defer s.mutex.Unlock()
При открытии файла мьютекс не нужен.

Здесь, на самом деле, лок будет очень долгим, потому что чтение -- дорогая операция

Есть два пути:
1. Оставить, как есть(только лок вынести на 62 строку)
2. Вычитать всё, что есть в файле, а потом уже проставить в мапу(под мьютексом)

2023-02-20 11:38 UTC, merged