[Increment3] Add new handlers for get metrics
iddanilov/metricsAndAlerting pull request #3
Opened 2022-07-12 15:46 UTC by iddanilov

2022-07-14 11:40 UTC, rktkov requested changes

2022-07-14 11:40 UTC, rktkov commented on internal/server/storage.go
> +	client "github.com/metricsAndAlerting/internal/models"
Порядок импортов надо изменить. См. пост - https://practicum-students.slack.com/archives/C03M8QT91D1/p1657701050055759

2022-07-14 11:40 UTC, rktkov commented on internal/server/storage.go
> +func (s *Storage) SaveGaugeMetric(metric client.GaugeMetric, mu *sync.Mutex) {
Мютекс стоит сделать частью структуры.

2022-07-14 11:40 UTC, rktkov commented on internal/server/storage.go
> +	mu.Unlock()
Если разблокировка мютекса последнее действие в методе, то лучше использовать конструкцию  defer

2022-07-14 11:40 UTC, rktkov commented on cmd/agent/main.go
> +		go func() {
Кажется в этом месте будут проблемы с использованием переменной metricValue. В момент когда сработает таймер отчета, несколько раз может сработать таймер сбора метрик и горутина отчета будет работать с последним собранным значением. Т.е. мы потенциально может потерять часть метрик.

2022-07-14 11:40 UTC, rktkov commented on cmd/server/main.go
> +	client "github.com/metricsAndAlerting/internal/models"
см. комментарий про очередность импорта.

2022-07-14 17:23 UTC, iddanilov commented on internal/server/storage.go
> +func (s *Storage) SaveGaugeMetric(metric client.GaugeMetric, mu *sync.Mutex) {
Поправил!

2022-07-14 17:24 UTC, iddanilov commented on internal/server/storage.go
> +	mu.Unlock()
Поправил!

2022-07-14 17:29 UTC, iddanilov commented on internal/server/handlers.go
> +func (h *handler) GetMetricsName(w http.ResponseWriter, r *http.Request) error {
Добавил проверку Write. Err нужен для соответствия функции appHandler, для работы с Middleware

2022-07-15 03:59 UTC, iddanilov commented on internal/server/handlers.go
> +		}, h.mu)
Вынес

2022-07-15 04:09 UTC, iddanilov commented on cmd/server/main.go
> +	client "github.com/metricsAndAlerting/internal/models"
+

2022-07-15 06:56 UTC, iddanilov commented on cmd/agent/main.go
> +		go func() {
Продублировал запись в параметр в горутине!

2022-07-15 06:56 UTC, iddanilov commented on cmd/server/main.go
> +	client "github.com/metricsAndAlerting/internal/models"
Поправил!

2022-07-18 22:03 UTC, rktkov requested changes

2022-07-18 22:03 UTC, rktkov commented on cmd/agent/main.go
> +		go func() {
Тогда надо убрать из внешнего кода, но проблема все равно сохраняется, теперь она с переменной runtimeStats.
У тебя 2 варианта исправления:
1. Все выполнять в горутине и переменные сделать видимыми только внутри нее, т.е. локальными сделать.
2. Изменить сигнатуру горутины, чтобы она принимал на вход как параметр metricValue, такой подход заставит рантайм скопировать значение в стек вызова горутины и проблем с переписыванием не будет.

2022-07-19 04:34 UTC, iddanilov commented on internal/agent/client.go
> +	apiKey     string
Убрал!

2022-07-19 04:34 UTC, iddanilov commented on internal/middleware/middleware.go
> +						w.WriteHeader(http.StatusInternalServerError)
+

2022-07-19 04:36 UTC, iddanilov commented on internal/server/handlers.go
> +func CreateResponse(s *Storage) string {
Сделал!

2022-07-19 04:37 UTC, iddanilov commented on internal/server/handlers.go
> +	urlValue := strings.Split(r.URL.Path, "/")
Переименовал, спасибо!

2022-07-19 04:39 UTC, iddanilov commented on internal/server/handlers.go
> +		w.WriteHeader(404)
Сделал!

2022-07-19 04:40 UTC, iddanilov commented on internal/server/storage.go
> +	defer s.Mutex.Unlock()
Сделал!

2022-07-19 04:42 UTC, iddanilov commented on internal/server/handlers.go
> +	router.HandlerFunc(http.MethodPost, update, middleware.Middleware(h.UpdateMetrics))
А есть пример? Я переделаю)

2022-07-19 17:46 UTC, iddanilov commented on internal/server/handlers.go
> +	router.HandlerFunc(http.MethodPost, update, middleware.Middleware(h.UpdateMetrics))
Не понял, как мне реализовать группу хендлеров. Могу создать новый middleware.Middleware с новым названием или имеется переделать реализацию Register?

2022-07-21 08:45 UTC, iddanilov commented on internal/server/handlers.go
> +	router.HandlerFunc(http.MethodPost, update, middleware.Middleware(h.UpdateMetrics))
Остановились на том, что текущий роутер не позволяет делать группировки. Решил сохранить текущую реализацию.

2022-07-22 15:42 UTC, rktkov approved these changes

2022-07-22 15:42 UTC, rktkov commented on cmd/agent/main.go
> +		go func() {
Этот вопрос все еще не решен. ПР приму, но в следующий раз если не разберемся с этим вопросом, ПР не буду аппрувить.

2022-07-23 10:27 UTC, merged