[increment4] Added new handlers
iddanilov/metricsAndAlerting pull request #4
Opened 2022-07-26 08:00 UTC by iddanilov

2022-08-04 21:24 UTC, rktkov requested changes

2022-08-04 21:24 UTC, rktkov commented on internal/server/handlers.go
> +	"github.com/gin-gonic/gin"
Порядок импортов нарушен.

2022-08-04 21:24 UTC, rktkov commented on internal/models/model.go
> +	Delta int64   `json:"delta,omitempty"` // значение метрики в случае передачи counter
Т.е. предполагается передача значения по умолчанию, если передается gauge? Еще не понятна логика объявления 2-х структур.

2022-08-04 21:24 UTC, rktkov commented on internal/server/handlers.go
> +	//urlValues := strings.Split(r.URL.Path, "/")
"Крошки со стола лучше убирать"

2022-08-04 21:24 UTC, rktkov commented on internal/server/config.go
> +	ADDRESS       *string        = flag.StringP("a", "a", "127.0.0.1:8080", "help message for flagname")
Зачем все имя в верхнем регистре?

2022-08-04 21:24 UTC, rktkov commented on internal/server/config.go
> +	RESTORE       *bool          = flag.BoolP("r", "r", true, "help message for flagname")
См. вопрос выше.

2022-08-04 21:24 UTC, rktkov commented on internal/handlers/handlers.go
>  package handlers
Какой-то очень лаконичный файл.

2022-08-04 21:24 UTC, rktkov commented on internal/agent/client.go
> +	ADDRESS        *string        = flag.StringP("a", "a", "127.0.0.1:8080", "help message for flagname")
Вопрос про регистр.

2022-08-04 21:24 UTC, rktkov commented on internal/agent/client.go
> +	err := env.Parse(&cfg)
Все что касается инициализации конфигурационной структуры лучше вынести в отдельный метод.

2022-08-04 21:24 UTC, rktkov commented on cmd/server/main.go
> +		for {
Не предусмотрен механизм корректного завершения горутины в момент завершения работы приложения.

2022-08-04 21:24 UTC, rktkov commented on cmd/agent/main.go
> +		metricValue := requestValue.SetMetrics(&runtimeStats)
Как будет осуществляться выход из цикла?

2022-08-06 13:26 UTC, iddanilov commented on internal/server/handlers.go
> +	"github.com/gin-gonic/gin"
Поправил!

2022-08-06 13:58 UTC, iddanilov commented on internal/models/model.go
> +	Delta int64   `json:"delta,omitempty"` // значение метрики в случае передачи counter
Убрал, структура и правда не нужна. После в 1to1 узнал, что указатели получают значение при маршеринге.

2022-08-06 14:04 UTC, iddanilov commented on internal/server/config.go
> +	ADDRESS       *string        = flag.StringP("a", "a", "127.0.0.1:8080", "help message for flagname")
Поправил!

2022-08-06 14:04 UTC, iddanilov commented on internal/server/config.go
> +	RESTORE       *bool          = flag.BoolP("r", "r", true, "help message for flagname")
Поправил!

2022-08-06 14:04 UTC, iddanilov commented on internal/agent/client.go
> +	ADDRESS        *string        = flag.StringP("a", "a", "127.0.0.1:8080", "help message for flagname")
Поправил!

2022-08-06 14:05 UTC, iddanilov commented on internal/handlers/handlers.go
>  package handlers
Убрал!

2022-08-06 19:51 UTC, iddanilov commented on cmd/server/main.go
> +		for {
Сделал!

2022-08-06 19:51 UTC, iddanilov commented on cmd/agent/main.go
> +		metricValue := requestValue.SetMetrics(&runtimeStats)
Сделал!

2022-08-06 19:53 UTC, iddanilov commented on internal/server/handlers.go
> +	//urlValues := strings.Split(r.URL.Path, "/")
Удалил!

2022-08-07 22:04 UTC, rktkov approved these changes

2022-08-15 18:18 UTC, merged